spring:
    batch:
        job:
            enabled: false
    jackson:
        default-property-inclusion: NON_NULL
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB 
    application:
        name: bowwow-api

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
        
public:
    data:
        api-key: nncudzgLg4qcJ5hIsIPMDizFbOefy2CdS6HALm8B+HEeymmgKZ6cI8w5c2qKnElE/2ZIYQf6EJUB0OF7d3c3AQ==
# Firebase
# firebase:
#     name: safe
#     id: safe-a112d
#     number: 677135268696