server:
    servlet:
        context-path: /api

spring:
    jackson:
        default-property-inclusion: NON_NULL
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB 
    application:
        name: bowwow-api

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace

# Firebase
# firebase:
#     name: safe
#     id: safe-a112d
#     number: 677135268696